### ISSUE TITLE
Promo Codes on Google Play not working for Lifetime products.

### ISSUE THREAD

**Issue by austinhodak** [adaptyteam/AdaptySDK-Android#12]
I'm having a weird issue and there's no way to contact support, so here I am. When a user redeems a promo code for a lifetime (non-consumable) product, nothing happens. Subscription promo codes work fine. I'm not sure if this is an Adapty issue or Google Play issue. Everything else has been implemented and working fine for months, except lifetime promo codes.

Any insight would be appreciated, thanks!

**Comment by austinhodak** [comment]
Bumping this. Can be reproduced by redeeming a promo code on a "Lifetime" item. Adapty shows no purchases and no entitlement while querying my own Billing Client shows the IAP from the redemption.

**Comment by vladd-g** [comment]
@austinhodak hi, is the issue still relevant with the newest version of the SDK?

**Comment by x401om** [comment]
I will close this issue, since there has been no answer for a long time. If the problem occurs again, feel free to reopen it.
