### ISSUE TITLE
Free trial period is set though not applicable (Android)

### ISSUE THREAD

**Issue by jobernolte** [adaptyteam/AdaptySDK-Android#14]
The `freeTrialPeriod` attribute in the `ProductModel` should only be set, if it is applicable. Right now it is always set even if I purchased the subscription before. Maybe its due to using an old version of the Google billing library on Android?

**Comment by vladd-g** [comment]
@jobernolte `freeTrialPeriod` always returns since it's taken from Billing Library, and Billing Library v4 returns it regardless whether it's applicable. You can use the `introductoryOfferEligibility` property for this purpose

**Comment by jobernolte** [comment]
`introductoryOfferEligibility` also always returns true. Is there any other possibility how I can obtain the correct information?

**Comment by jobernolte** [comment]
Regarding the screenshot: I already bought this product several times and the free trial period is no longer applicable.

**Comment by jobernolte** [comment]
I found a workaround for this: I just check the `PurchaserInfoModel` if the user had any subscriptions of the given product and omit the free trial period if so.
