### ISSUE TITLE
Adapty SDK is leaking resources

### ISSUE THREAD

**Issue by jobernolte** [adaptyteam/AdaptySDK-Android#15]
![Screenshot 2022-08-03 155446](https://user-images.githubusercontent.com/208996/182626029-263089f1-1685-44ac-b2d9-602928b5e3db.png)

**Comment by vladd-g** [comment]
@jobernolte could you please provide full stacktrace?

**Comment by vladd-g** [comment]
@jobernolte what's the device and android os version where you encountered the problem?

**Comment by jobernolte** [comment]
It's the Android Studio emulator using API Version 29

**Comment by jobernolte** [comment]
I think it's the following code in the SDK which is leaking (HttpResponseManager.kt):

`    private fun toStringUtf8(inputStream: InputStream, isInGzip: Boolean): String {
        val reader = BufferedReader(
            InputStreamReader(
                if (isInGzip) GZIPInputStream(inputStream) else inputStream,
                Charsets.UTF_8
            )
        )
        val total = StringBuilder()
        var line: String? = reader.readLine()
        while (line != null) {
            total.append(line).append('\n')
            line = reader.readLine()
        }
        return total.toString()
    }
`

**Comment by jobernolte** [comment]
If you're using an `InputStream` you should call `close()` when you're done with it.

**Comment by vladd-g** [comment]
> I think it's the following code in the SDK which is leaking (HttpResponseManager.kt):
> 
> ` private fun toStringUtf8(inputStream: InputStream, isInGzip: Boolean): String { val reader = BufferedReader( InputStreamReader( if (isInGzip) GZIPInputStream(inputStream) else inputStream, Charsets.UTF_8 ) ) val total = StringBuilder() var line: String? = reader.readLine() while (line != null) { total.append(line).append('\n') line = reader.readLine() } return total.toString() }`

Due to stacktrace it is, thank you! We'll fix it.

**Comment by vladd-g** [comment]
@jobernolte fixed in 1.12.0

**Comment by jobernolte** [comment]
Thanks!
