### ISSUE TITLE
Android Billing Library v5 REQUIRED for all app updates after November 1st

### ISSUE THREAD

**Issue by zholmes1** [adaptyteam/AdaptySDK-Android#21]
![Screenshot_20230526_091013_Brave.jpg](https://github.com/adaptyteam/AdaptySDK-Android/assets/3410114/578e13d2-93e5-4eab-a06b-72a30d96f9ea)

This is not a drill. Adapty must roll out updates for their SDK's ASAP. The worst thing for Adapty would be to try to roll this out last minute and then have some kind of major bug surface after the deadline has already passed. Get this upgrade done now so we can at least roll back to an older version if we have to.

Clock's ticking!

**Comment by vladd-g** [comment]
Answered in #13
