### ISSUE TITLE
Android Lifecycle integration

### ISSUE THREAD

**Issue by krottv** [adaptyteam/AdaptySDK-Android#4]
It would be nice to have android lifecycle integration for methods life Adapty.getPaywalls to avoid receiving callback when a component is destroyed.

**Comment by vladd-g** [comment]
@krottv Thank you for the feedback! But methods can be called from the entity whose lifecycle is different from activity's or fragment's one, so you get the result immediately from, say, ViewModel after changing configuration. Or I misunderstood your idea, could you please specify the case with more details?

**Comment by krottv** [comment]
@vladd-g 
My case is just getting paywalls in activity to display it. Yes, seems like I need to use ViewModel. Thanks.
