### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException Attempt to invoke virtual method 'java.lang.String org.json.JSONObject.optString(java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by SlavaKukhto** [adaptyteam/AdaptySDK-Android#9]
Hi guys! Please, help me! I am using your library.
After upgrading from version 0.9.3 to 1.4.0 on production, I started getting crash.

> 
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.json.JSONObject.optString(java.lang.String)' on a null object reference
       at com.android.billingclient.api.SkuDetails.getPrice(SkuDetails.java:4)
       at com.everydoggy.android.presentation.view.fragments.purchase.PurchaseHFragment.processLeftBlockSubscription(PurchaseHFragment.java:3)
       at com.everydoggy.android.presentation.view.fragments.purchase.-$$Lambda$PurchaseHFragment$KebSxts6iHh6Z1vGaFVTwikCdJs.onChanged(-.java:3)
       at androidx.lifecycle.LiveData.considerNotify(LiveData.java:29)
       at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:15)
       at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:23)

> 

It is very similar to this https://github.com/adaptyteam/AdaptySDK-Android/issues/5.

The field description says that it cannot be null. But based on the crash, it can.
Maybe you could suggest how you can try to fix it?

Thanks

**Comment by vladd-g** [comment]
@SlavaKukhto hi, the crash happened on Billing Library level, I suppose it's also an obfuscation issue and can be handled the same way as #5 
please try adding -keep class com.android.billingclient.** { *; } to your proguard config

**Comment by SlavaKukhto** [comment]
@vladd-g Yes, I read the comments and added this line to proguard config. But, unfortunately, it does not help.

**Comment by SlavaKukhto** [comment]
@vladd-g I have an assumption that this is somehow connected with the cache that you store and with the update of the google billing library. Perhaps when Google updated their library, they changed the data format.
I reproduce the crash in the following steps.
1 ) Install the version of the application with adapty 0.9.4 (google billing v 3)
2) Open purchase screen for get info about subscriptions
3) Update the application to adapty 1.4.0 (google billing v 4)
4) Turn off the internet
5) Open the application
6) Crash

**Comment by vladd-g** [comment]
Have you performed 'clean' before rebuilding? And do you have this crash without proguard? Because there is no idea why this can happen other than obfuscation, since the crash initially occurs inside `SkuDetails` class in the place where behaviour doesn't depend on our code

**Comment by vladd-g** [comment]
@SlavaKukhto If you fresh-install the build starting from "3)", everything's ok?

**Comment by vladd-g** [comment]
I don't believe in migration problems since lots of apps migrate from Billing Library v3 to v4, crashes would have been everywhere then

**Comment by SlavaKukhto** [comment]
It's really interesting. I can not reproduce on debug.
But this line (-keep class com.android.billingclient.** { *; }) is definitely added to the proguard rule.
There are no problems with a clean installation of the application with the adapty version 1.4.0.
Thank you, I will follow.

**Comment by SlavaKukhto** [comment]
This crash no longer appears. I close this issue.
